### ISSUE TITLE
Отзыв о курсе

### ISSUE THREAD

**Issue by cpython-projects** [cpython-projects/tg-bot-aug-team#10]
Написать функцию, которая добавляет в файл comments.txt отзыв о прослушанном курсе. От одного пользователя принимается только один отзыв.
Формат записи:
название_курса;студент;комментарий (не более 500 символов)

**Comment by BrogramUltimate** [comment]
Sowwy!! Ouw code monkas are wowking vewy hawd!!!

**Comment by BrogramUltimate** [comment]
done
